/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 */

plugins {
    id("java")
    id("war")
}

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_19
    targetCompatibility = JavaVersion.VERSION_19
}

dependencies {
    compileOnly("jakarta.servlet:jakarta.servlet-api:6.0.0")
}

val war: War = tasks.named<War>("war") {
    archiveFileName = "baggiodev.war"
}.get()

val deployTomcatTask: Task = task("deployTomcat", type = Copy::class) {
    group = "build"
    from(war.archiveFile)
    into("/Users/baggio/Applications/apache-tomcat-9.0.43/webapps")
}

deployTomcatTask.dependsOn(war)

val assembleTask: Task = tasks.first { it.name == "assemble" }

assembleTask.dependsOn(deployTomcatTask)
