/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 */


val task = task("link") {
    println("Project linking has finished")
    group = "build setup"
    doFirst {
        println("Project linking has finished")
    }
}